lint:
  files_unchanged:
    - assets/nf-core-epitopeprediction_logo_light.png
    - docs/images/nf-core-epitopeprediction_logo_light.png
    - docs/images/nf-core-epitopeprediction_logo_dark.png
    - .vscode/settings.json
template:
    skip_features:
        - fastqc
        - igenomes
nf_core_version: 3.4.1
repository_type: pipeline
template:
  author: Christopher Mohr, Jonas Scheid
  description: A fully reproducible and state of the art epitope prediction pipeline.
  force: false
  is_nfcore: true
  name: epitopeprediction
  org: nf-core
  outdir: .
  version: 3.1.0
