lint:
  files_unchanged:
    - assets/nf-core-epitopeprediction_logo_light.png
    - docs/images/nf-core-epitopeprediction_logo_light.png
    - docs/images/nf-core-epitopeprediction_logo_dark.png
    - .vscode/settings.json
nf_core_version: 3.5.1
repository_type: pipeline
template:
  author: Christopher Mohr, Jonas Scheid
  description: A fully reproducible and state of the art epitope prediction pipeline.
  force: false
  is_nfcore: true
  name: epitopeprediction
  org: nf-core
  outdir: .
  skip_features:
    - fastqc
    - igenomes
  version: 3.2.0dev
